version: 0.2

env:
  variables:
    AWS_SDK_LOAD_CONFIG: 1

phases:
  install:
    commands:
      - echo Installing build dependencies...
  build:
    commands:
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Packaging artifacts...
      - zip -r build_output.zip index.html appspec.yml scripts/

artifacts:
  files:
    - build_output.zip
  discard-paths: yes
